version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: |
          git clone -b master https://github.com/project-sunbird/genie-sdk-wrapper.git
          cd genie-sdk-wrapper
          rm package-lock.json
          npm install
          npm run build
          rm $(pwd)/dist/dependencies.json
          npm pack $(pwd)/dist
          cd ..
          npm install
          npm install $(pwd)/genie-sdk-wrapper/*.tgz --save
          rm -rf genie-sdk-wrapper

