version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: |
          CORDOVA_COUNTER=0
          SUNBIRD_CORDOVA_COUNTER=0
          file="./build_config"
          while IFS="=" read -r key value; do
            case "$key" in
            '#'*) ;;
            'cordova'*)
              CORDOVA[$CORDOVA_COUNTER]=$value
              CORDOVA_COUNTER=$((CORDOVA_COUNTER+1));;
            'sunbird-cordova'*)
              SUNBIRD_CORDOVA[$SUNBIRD_CORDOVA_COUNTER]=$value
              SUNBIRD_CORDOVA_COUNTER=$((SUNBIRD_CORDOVA_COUNTER+1));
            esac
          done < "$file"
          echo $CORDOVA_COUNTER
          which git
      #- run: |
          #git clone -b master https://github.com/project-sunbird/genie-sdk-wrapper.git
          #cd genie-sdk-wrapper
      #     rm package-lock.json
      #     npm install
      #     npm run build
      #     rm $(pwd)/dist/dependencies.json
      #     npm pack $(pwd)/dist
      #     cd ..
      #     npm install
      #     npm install $(pwd)/genie-sdk-wrapper/*.tgz --save
      #     rm -rf genie-sdk-wrapper
      # - run: |
      #     sudo npm install -g ionic cordova
    
      #     for cordova_plugin in "${CORDOVA[@]}"
      #     do
      #       ionic cordova plugin add $cordova_plugin
      #     done
      #     for cordova_plugin in "${SUNBIRD_CORDOVA[@]}"
      #     do
      #       ionic cordova plugin add $cordova_plugin#$buildBranch
      #     done
      #     rm -rf platforms
      # - run: |
      #     ionic cordova platforms add android@7.0.0
      #     ionic cordova build android