version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run:
        name: Installing genie-sdk-wrapper
        command: |
          git clone -b $buildBranch https://github.com/project-sunbird/genie-sdk-wrapper.git 
      - run: npm run test:ci

